micronaut:
  application:
    name: keyManagerGRPC
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanager
    driverClassName: org.postgresql.Driver
    username: keymanager
    password: keymanager
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update

javax:
  validation:
    constraints:
      ChavePixValidaValidator:
        message: chave pix invalida